### ISSUE TITLE
How to show the country value was choose to front-end

### ISSUE THREAD

**Issue by trantin2310** [nlemoine/acf-country#10]
I want to show value of country was chosen from back-end to front-end

i was using this code

get_field(‘country_selling’); // country_selling are field name when setup

but it show value NULL

can you guide me how to show value of country was chosen.

**Comment by nlemoine** [comment]
Hello, 

Sorry, this is not an ACF country issue.

**Comment by trantin2310** [comment]
Yes i know. But can you help guide me how to show value to frontend.?.
