### ISSUE TITLE
the empty option not working if choose country and then remove it for update

### ISSUE THREAD

**Issue by trantin2310** [nlemoine/acf-country#11]
the empty option not working for me after you fixed.

please check with screenshot and i will you login website detail for you checking.
login:
http://122.201.118.65/~pickadevelop/wp-admin/
username: admin
password: admin

check image link
https://www.awesomescreenshot.com/image/3115175/51ec6fa8dad0f5043b5b4894202dc3cd
check product link with country file called country_selling
http://122.201.118.65/~pickadevelop/wp-admin/post.php?post=96696&action=edit

hope you will help me solve soon.

**Comment by trantin2310** [comment]
hello I was waiting the update from you. Hope you will help solve this bug soon.

Thanks again

**Comment by nlemoine** [comment]
@trantin2310 

I just released an update of ACF Country. Let me know if you still encounter this bug.
