### ISSUE TITLE
Multiple countries selected shows no countries, affects any new post thereafter

### ISSUE THREAD

**Issue by s7media** [nlemoine/acf-country#12]
Hi there, love this little plugin, thank you!

I've noticed that if I select multiple countries (so the field is set as multiple choice), my template will not show any country at all. Also, going forward, creating new posts with a country set in the country field will not show the country in the template for that newer post, even though only one country is selected.

What I've had to do now is remove the multiple choice option, and then had to go back to the newer posts, and reselect the country (as none was set - the default selection was Afghanistan).

I can link if required.

**Comment by nlemoine** [comment]
Just released a huger update. Let me know if you encounter this bug.
