### ISSUE TITLE
Countries flags not loaded

### ISSUE THREAD

**Issue by uprise10** [nlemoine/acf-country#15]
I'm using this plugin with ACF Pro 5.6.9, but the flags are not loaded.

When I dive, this probably is because a change in Select2, see https://select2.org/upgrading/migrating-from-35#renamed-templating-options.

However, just renaming these options (from `formatResult` to templateResult`` for instance) won't work. I get unparsed HTML (http://upload.uprise.nl/Jy8h67) and other JS errors (non-existing methods in `$.fn.select2.defaults`).

**Comment by thibaudalt** [comment]
+1

**Comment by nlemoine** [comment]
Hi @uprise10 and @thibaudalt 

Just released an update that should fix flags issues. 

Let me know if you still having missing flags.

**Comment by uprise10** [comment]
Awesome, works like a charm again!
