### ISSUE TITLE
Not working with ACF Pro 5.7.6

### ISSUE THREAD

**Issue by meliloop** [nlemoine/acf-country#20]
Details
-------

 - WordPress version: 4.9.8
 - ACF version: Pro 5.7.6
 - For UX/UI issues: Chrome Versión 69.0.3497.100

Reproduction
------------

Not working. Showing this error on console

acf-country.js?ver=1.1.0:56 Uncaught TypeError: Cannot read property 'extend' of undefined
    at acf-country.js?ver=1.1.0:56
    at acf-country.js?ver=1.1.0:127

**Comment by peterStoj** [comment]
Getting the same issue. Both Production and staging environment but on my local environment it doesn't come up with the error.

**Comment by nlemoine** [comment]
Hi @meliloop 

Yes, I'm aware of this issue. Unfortunately, I don't any time to fix this right now. 

I'll close this issue as soon as it is resolved.

**Comment by nlemoine** [comment]
@meliloop 

ACF Country is now compatible with ACF 5.7+

Let me know if you stumble upon bugs.
