### ISSUE TITLE
Country code received instead of country name as selected

### ISSUE THREAD

**Issue by albertonieto** [nlemoine/acf-country#22]
When I create a custom object with ACF and I add to it a country field using this plugin I can select the Return Format:
![Screenshot 2019-04-16 at 10 43 15](https://user-images.githubusercontent.com/5978156/56196884-05029080-6038-11e9-9b58-3ed63d0faa1e.png)

When I select Country name as the return format I can see that working on the backend:
![Screenshot 2019-04-16 at 10 43 46](https://user-images.githubusercontent.com/5978156/56196913-1055bc00-6038-11e9-9f47-1948639454ec.png)

However it doesn't seem to work on the frontend:
![Screenshot 2019-04-16 at 10 44 27](https://user-images.githubusercontent.com/5978156/56196932-19468d80-6038-11e9-8809-7b69c1d91308.png)

I use FacetWP to search through my custom objects, and when I specify the Data source as the object that contains the country value, it returns the Country code instead of the Country name as specified:
![Screenshot 2019-04-16 at 10 48 25](https://user-images.githubusercontent.com/5978156/56196950-23688c00-6038-11e9-9936-186bfca9efd5.png)

 - WordPress version: 5.1.1
 - ACF Pro version: 5.7.12
 - ACF Country version: 2.0.0
 - FacetWP version: 3.3.5

**Comment by nlemoine** [comment]
Hello @albertonieto, 

Outside FacetWP, ACF Country works as expected (I just tested all returned formats). This an issue related to FaceWP.

**Comment by albertonieto** [comment]
Hi @nlemoine,
I am in conversations with the FacetWP plugin guys but we are not solving this. Can you maybe point us to the right direction? Here is the code they suggested:
```
// Grab the country code => name mapping
add_action( 'acf/country/countries', function( $countries ) {
    FWP()->acf_countries = $countries;
    return $countries;
});
// Replace the country code with the name
add_filter( 'facetwp_acf_display_value', function( $value, $params ) {
    $country_code = $params['facet_value'];
    return FWP()->acf_countries[ $country_code ];
}, 10, 2 );
```

The idea was to get the country code and replace it with the country name before it gets saved on the FacetWP table on the database. However, we are saving always an empty value instead of the country name on the database. Any idea?

**Comment by albertonieto** [comment]
Hi,
I was able to build a workaround but is not very sustainable since it uses a hardcoded list of countries instead of the one provided by your plugin. Here is my code:

```
/* ---------------------------------------------
ACF Country saves Country name to be displayed on FacetWP
--------------------------------------------- */
//Ref: https://facetwp.com/documentation/developers/indexing/facetwp_index_row/
add_filter( 'facetwp_index_row', function( $params, $class ) {
  if ( $params['facet_name'] == 'country' ) {
    $countryList = array (
      'AF' => 'Afghanistan',
      'AX' => 'Åland Islands',
      etc...
    );
    foreach ($countryList as $key => $value) {
      if ( strtoupper($params['facet_value']) == $key ) {
        $params['facet_display_value'] = $value;
        $class->insert( $params ); // insert new value to the database
      }
    }
  }
  return $params;
}, 10, 2 );
```

It would be great if we find a way to use the list of countries provided by your plugin (`plugins/acf-country/en/country.php`) instead of this hardcoded `$countryList`.

**Comment by nlemoine** [comment]
Hi @albertonieto, 

I only know FacetWP by name, I never used it but I think you should probably avoid saving country name in the FacetWP table. It's always better to save ID's ou ID's like (country code in this case). You should look for an "output" filter. 

I quickly looked into FacetWP source. I think the "right" value of the country field isn't loaded correctly because FacetWP only takes care of known ACF fields (see `facetwp/includes/integrations/acf/acf.php`). ACF Country is a "country" type field, FacetWP don't know anything about it, hence, the raw database value is returned. 

Try to use this filter `facetwp_acf_display_value`.

```php
add_filter('facetwp_acf_display_value', function($value, $params) {
    if($params['name'] !== 'your_field_name') {
        return $value;
    }
    // get country translations
    $country_field_object = get_field_object('country');
    $countries = $country_field_object['choices'];
    return $countries[$value];
}, 10, 2);
```

This is untested. You should adapt it to your needs.

**Comment by albertonieto** [comment]
This fixed it for me:
```
add_filter( 'facetwp_acf_display_value', function( $value, $params ) {
    if ( 'country' == $params['facet_name'] ) {
        $post_id = (int) $params['post_id'];
        $country_code = $params['facet_value'];
        $country_field_object = get_field_object( 'country', $post_id );
        $countries = $country_field_object['choices'];
        return $countries[ $value ];
    }
    return $value;
}, 10, 2 );
```

**Comment by nlemoine** [comment]
Glad you made it work. 

"Thanks" might have been appropriate.
