### ISSUE TITLE
Add new country key and value

### ISSUE THREAD

**Issue by tinyMeerkatRebel** [nlemoine/acf-country#25]
Hello and I am really sorry for creating an issue but I am not so sure how else I can get in touch with you!

I want to add a new country field; I've read in the `README` file that I can do that by using this function:

```
You can remove (or add) some countries with the acf/country/countries filter, example:

add_filter( 'acf/country/countries', function( $countries ) {
	return array_filter( $countries, function( $code ) {
		return !in_array( $code, ['IC', 'EA'], true );
	}, ARRAY_FILTER_USE_KEY);
} );
```

However, I am only able to remove a country by its code but I am not so sure how to add a new country name and code?

I've tried merging or adding a new pair of key & value into the array of countries but it did not work. 

If you could please let me know? And I am sorry for any inconvenience.

Thanks,
Marina

**Comment by nlemoine** [comment]
```php
add_filter( 'acf/country/countries', function( $countries ) {
    $countries['ZL'] = 'Zombie Land';
    return $countries;
} );
```
Should do the trick.
