### ISSUE TITLE
Countries not being returned as value label array

### ISSUE THREAD

**Issue by dontdomilk** [nlemoine/acf-country#30]
Details
-------

- WordPress version: 5.4.2
- ACF version: 5.8.12 (Pro)
- For UX/UI issues: Mac, Chrome 83.0.4103.97
- Multiple: False

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Only country codes are being returned. I selected 'Country code and name' as the return format, but I received a country code string. I tested 'Country name' as well, but stll was left with the country code after updating posts.

### Steps to reproduce

- Add new country field 
- Choose 'Country code and name' as the return format
- Choose country on post
- Query post meta and check results

### Actual result

Received country code

### Expected result

Receive country code and name in array

**Comment by nlemoine** [comment]
I can't reproduce the bug. Everything is working as expected for me. Could you add more informations (code, etc.)? Are you sure you're using the `get_field` method?
