### ISSUE TITLE
Doesn't have option for GraphQL. All other fields from ACF currently support GraphQL. 

### ISSUE THREAD

**Issue by Ninodevo** [nlemoine/acf-country#33]
It's with this plugin https://github.com/wp-graphql/wp-graphql-acf. Can you maybe add support?

**Comment by Ninodevo** [comment]
Hi only this needs to be added to the plugin and everything works. I've forked it for now but can you. Add it in the next update. And I found a bug - when you change the return format it always returns the value


            add_filter('wpgraphql_acf_supported_fields', function ($supported_fields) {
			array_push($supported_fields, 'country');
			return $supported_fields;
		});

		add_filter('wpgraphql_acf_register_graphql_field', function ($field_config, $type_name, $field_name, $config) {

			// How to add new WPGraphQL fields is super undocumented, I used this code as a base
			// https://github.com/wp-graphql/wp-graphql/issues/214#issuecomment-653141685

			$acf_field = isset($config['acf_field']) ? $config['acf_field'] : null;
			$acf_type = isset($acf_field['type']) ? $acf_field['type'] : null;

			$resolve = $field_config['resolve'];

			if ($acf_type === "country") {

				if (! empty( $acf_field['return_format'] ) && $acf_field['return_format'] === 'array') {
					$field_config = [
						'type' =>  [ 'list_of' => 'String' ],
						'resolve' => function ($root, $args, $context, $info) use ($resolve) {
							$value = $resolve($root, $args, $context, $info);
							return ! empty( $value ) && is_array( $value ) ? $value : [];
						}
					];
				} else {
					$field_config = [
						'type' => 'String',
						'resolve' => function ($root, $args, $context, $info) use ($resolve) {
							$value = $resolve($root, $args, $context, $info);
							return ! empty( $value ) ? $value : null;
						}
					];
				}


			}

			return $field_config;
		}, 10, 4);

**Comment by nlemoine** [comment]
PR please

**Comment by nlemoine** [comment]
Thanks @Ninodevo!

This is merged. I slightly changed your PR. This is untested, can you give it a try on `2.x` branch and tell me if everything is ok?

**Comment by Ninodevo** [comment]
Hi @nlemoine 
Everything is working fine! :) thanks for the merge.
