### ISSUE TITLE
Are you planning to add this plugin to the WordPress Plugin Directory?

### ISSUE THREAD

**Issue by gsusI** [nlemoine/acf-country#34]
As the title states, are you planning to add this plugin to the WordPress Plugin Directory? I'd be awesome.

Thanks

**Comment by nlemoine** [comment]
I already try to submit it but it was refused. ACF fields plugin type are not considered as true plugins.

**Comment by gsusI** [comment]
That is certainly unfortunate. Using that threshold, the Plugins Directory
would have half the plugins it currently has 😂
