### ISSUE TITLE
Option for other languages

### ISSUE THREAD

**Issue by meugamer** [nlemoine/acf-country#43]
I use it on my website, however, I have to change all country names to Brazilian Portuguese. Is there a way to put the language option in order to be able to write the name of each country in the native language that is used?

**Comment by nlemoine** [comment]
I'm not sure to understand what your issue is. ACF country is already returning country names in your language: https://github.com/nlemoine/acf-country/blob/2.0/fields/acf-country.php#L259

**Comment by meugamer** [comment]
I updated the latest version and the countries are translated!

I have another question. How could I display multiple country flags using multiple selection. Would you have any sample code? Since whenever I try, one country appears and not several.
