### ISSUE TITLE
Usable in Conditional Logic

### ISSUE THREAD

**Issue by leolll** [nlemoine/acf-country#5]
Any way to make the Country field type available for Conditional Logic?  Currently, ACF doesn't consider it a toggle field.

**Comment by nlemoine** [comment]
Hi @leolll 

ACF currently doesn't provide an official (and handy) way to handle conditional logic in custom field types (see the issue referenced above, ACF author said this is planned for this year). 

Anyway, I figured something out to make this work in the meantime (only works on v5/pro). 

Can you please test this before I release it? You can download the conditional logic enabled version on this branch: https://github.com/nlemoine/acf-country/tree/feature-conditional

**Comment by leolll** [comment]
@nlemoine Thanks for taking a look at this.  I've only got v4 installed so I can't help test this.

**Comment by nlemoine** [comment]
@leolll 
I enabled conditional logic for ACF v4. Can you test it?

**Comment by leolll** [comment]
@nlemoine Works great!  Tried it with multiple field types using "is equal to" & "is not equal to" and it worked in all cases.

**Comment by nlemoine** [comment]
Thanks for your feedback! I'll release a new version today.

**Comment by violllettta** [comment]
Hi there, 

Is it possible to use code snippets to apply your conditionalerizer to another custom field (that currently doesn't allow itself to be selected for conditional logic), specifically user_role:

Here in github: https://github.com/danielpataki/ACF-Role-Selector
Plugin: https://wordpress.org/support/plugin/acf-role-selector-field/



Thank you!
Violet
