### ISSUE TITLE
How do you keep country names up-to-date?

### ISSUE THREAD

**Issue by szepeviktor** [nlemoine/acf-country#53]
Hello!

What is the data source you use to keep the country list fresh?
Thank you.

**Comment by nlemoine** [comment]
Hello @szepeviktor, 

Right here: https://github.com/nlemoine/acf-country/blob/3344d80861412895d2f8f9e9cb89dadf631ec31a/composer.json#LL51C18-L51C18

The data is coming from this package: https://github.com/umpirsky/country-list

**Comment by szepeviktor** [comment]
I see.
Thank you.

That packages gets it from `symfony/intl` and Symfony gets it from https://github.com/unicode-org/icu

**Comment by nlemoine** [comment]
I was using symfony/intl at first, don't remember why I switched. I'll have a look again at this when I have some time. `symfony/intl` might be better maintained.

**Comment by szepeviktor** [comment]
~~... maybe you can publish your upgrade script too~~

https://github.com/nlemoine/acf-country/blob/3344d80861412895d2f8f9e9cb89dadf631ec31a/composer.json#L51-L53

**Comment by nlemoine** [comment]
Was about to ask ^^
