### ISSUE TITLE
Flags not loading

### ISSUE THREAD

**Issue by SpenMillard** [nlemoine/acf-country#6]
Hi there,

The plugin works great but the flags are not loading - do they need to be switched on? 

All dependent files are present and have loaded properly.

Thanks

![country_markup](https://user-images.githubusercontent.com/457918/32295885-75c31904-bf42-11e7-8373-804c35ff6b6f.png)

**Comment by nlemoine** [comment]
Hi @SpenMillard,

Flags don't need to be switched on and you should see them. 

Your screenshot shows that fonts are not loaded too. I never had such feedback and am pretty sure it's a local issue from your setup. I'm closing the issue for now. 

Try to have a look at the network tab in Chrome to see if the flags sprite loads.

**Comment by SpenMillard** [comment]
Thanks for getting back - yes, I thought they should appear by default too.

I looked through the code and the following markup is not being loaded from acf-country.js:

`<span class="acf-country-flag-icon famfamfam-flags ' + code + '"></span> <span class="acf-country-flag-name">' + country + '</span>'`

Is this meant to appear within `<li class="select2-results__option"...`?

Kind regards,

Spencer

**Comment by nlemoine** [comment]
Can you tell me more about your environment (OS, browser, WordPress version, etc.)? Your screenshot shows errors in the console, can you show them?

**Comment by SpenMillard** [comment]
Hi Nico,

Thanks for getting back to me.

I have the following set up:

OSX Sierra: 	10.12.6
Safari:		11.0.1
Wordpress: 	4.8.3

I have attached the error grab form the console tab (console.png) - they only refer to the Evernote extension.

the acf-country.js file is loading (see other attached image acf-country.png) which is meant to load the flag markup. Strange, isn’t it?

I have also attached a grab of the front-end markup - you can see each country inside the <li> but the flag is missing, which I presume should appear within the <li>?

Kind Regards,

Spencer

**Comment by SpenMillard** [comment]
Hi Nico,

I re-uploaded my screen grabs from my previous message - I wasn't certain you received them.

Regards,

Spencer

**Comment by nlemoine** [comment]
Hi @SpenMillard, 

You seem to be using ACF in a strange context. Why do the field appear on the front end? It's not supposed to. Why `acf-country.js` is loaded from a `Scripts` folder that doesn't even exist in this repo?

Looks like an edge case to me.

**Comment by SpenMillard** [comment]
Hi Nico,

Yes, I am using your plugin for a front-end form - why would this affect the flags appearing?

I installed the plugin via the CMS, as I would normally.

Cheers,

**Comment by nlemoine** [comment]
> Yes, I am using your plugin for a front-end form

That's something it would have been worth to know ^^ Is this something ACF provides or are you using a plugin to achieve this?

> why would this affect the flags appearing?

Probably because it does not resolve flags paths.

**Comment by SpenMillard** [comment]
Sorry Nico, I didn't realise it was relevant.

Yes, this is something ACF provides for using: `<?php acf_form_head(); ?>`

Any idea how I can resolve the flag paths? All the correct files appear to be loading, but this is not being injected into the page:

`<span class="acf-country-flag-icon famfamfam-flags ' + code + '"></span> <span class="acf-country-flag-name">' + country + '</span>'`

Strange, isn't it?

Regards,

Spencer

**Comment by nlemoine** [comment]
I don't know how ACF handles fields assets on the front end and this would require some testing (setting up a test case, figure out what's going wrong, etc.). If you can provide a test case, I may have a look at it. I'm sorry but this is a plugin I built for a project and open sourced so some people could benefit from it but I don't use it anymore and can't spend more time on it.
