### ISSUE TITLE
rename v3 main plugin file

### ISSUE THREAD

**Issue by joostdekeijzer** [nlemoine/acf-country#62]
Details
-------

 - WordPress version: v6.4.3
 - ACF version: v6.2.2 Pro

Reproduction
------------

Testing v3 branch I've updated the plugin through composer from v2.1.0 to v3.x-dev.

Because the main plugin file is renamed I get the following error in the WordPress plugins overview:

<img width="790" alt="image" src="https://github.com/nlemoine/acf-country/assets/216672/582b60c1-bef5-4094-b64b-06d895e0b892">

Renaming the main plugin file from `plugin.php` to `acf-country.php` should fix this and make a more seamless version update possible.

**Comment by joostdekeijzer** [comment]
(did a quick test by renaming the file manually directly after `composer update` and renaming does resolve this issue for me)

**Comment by nlemoine** [comment]
Hello @joostdekeijzer, 

I did some cleanup, can you try latest 3.x branch and tell me if it's working for you? Than I can merge #63 and 3.0 is released.

**Comment by joostdekeijzer** [comment]
With PHPv8.1 I get

`PHP Fatal error:  Type of HelloNico\AcfCountry\CountryField::$show_in_rest must not be defined (as in class acf_field) in public_html/wp-content/plugins/acf-country/src/CountryField.php on line 0`

Removing code below from `CountryField.php` solves it.
```php
    /**
     * Isn't needed because we're extending acf_field, but it's here for clarity.
     *
     * @var boolean
     */
    public bool $show_in_rest = true;
```

**Comment by joostdekeijzer** [comment]
Other than that the upgrade works fine

**Comment by nlemoine** [comment]
Just removed the type, seems to work fine, you can update and tell me everything's ok from your side?

**Comment by joostdekeijzer** [comment]
All OK here :)

**Comment by nlemoine** [comment]
Let's release it then! :)

**Comment by joostdekeijzer** [comment]
💪
