### ISSUE TITLE
Conflict with Admin Columns Pro

### ISSUE THREAD

**Issue by dbrabyn** [nlemoine/acf-country#64]
Details
-------

 - WordPress version: [ 6.4.3 ]
 - ACF version: [ ACF Pro 6.2.7 ]
 - For UX/UI issues: [ macOS Sonoma 14.3.1, Safari 17.3.1 ]
 - Allow null: [ true ]
 - Multiple values: [ false ]
 - Stylised UI: [ true ]
 - Condtional logic: [ false ]
 - Admin Columns Pro version: [ 6.4.6 ]

Reproduction
------------

Add any new Admin Columns Pro column to an All posts or CPTs list page with ACF Country v3.0.0 activated and you will see a fatal error message in that column.

No JS error.

### Bug summary

Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, cannot access protected method class@anonymous::admin_column() in /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-includes/class-wp-hook.php:324 Stack trace: #0 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-includes/plugin.php(205): WP_Hook->apply_filters('\n\t\t<span class=...', Array) #1 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-content/plugins/admin-columns-pro/admin-columns/classes/Table/ManageValue.php(50): apply_filters('ac/column/value', '\n\t\t<span class=...', 671, Object(ACP\Column\Post\FeaturedImage)) #2 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-content/plugins/admin-columns-pro/admin-columns/classes/Table/ManageValue/Post.php(39): AC\Table\ManageValue->render_cell('64d114cfe872b0', 671) #3 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-includes/class-wp-hook.php(324): AC\Table\ManageValue\Post->render_value('64d114cfe872b0', 671) #4 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #5 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #6 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-admin/includes/class-wp-posts-list-table.php(1398): do_action('manage_rider_po...', '64d114cfe872b0', 671) #7 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-admin/includes/class-wp-list-table.php(1799): WP_Posts_List_Table->column_default(Object(WP_Post), '64d114cfe872b0') #8 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-admin/includes/class-wp-posts-list-table.php(1432): WP_List_Table->single_row_columns(Object(WP_Post)) #9 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-admin/includes/class-wp-posts-list-table.php(834): WP_Posts_List_Table->single_row(Object(WP_Post), 0) #10 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-admin/includes/class-wp-posts-list-table.php(810): WP_Posts_List_Table->_display_rows(Array, 0) #11 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-admin/includes/class-wp-list-table.php(1709): WP_Posts_List_Table->display_rows() #12 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-admin/includes/class-wp-list-table.php(1636): WP_List_Table->display_rows_or_placeholder() #13 /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-admin/edit.php(503): WP_List_Table->display() #14 {main} thrown in /Users/davidbrabyn/Local Sites/roland-cycling-team/app/public/wp-includes/class-wp-hook.php on line 324

Given this info, support at ACP tell me: "The following hook throws an error and that should only occur if the hook in our plugin is used incorrectly: 'ac/column/value'."

### Expected result

Peaceful coexistence. Normal display of Admin Columns pro columns and a super useful country field in ACF.

**Comment by nlemoine** [comment]
Hello @dbrabyn, 

I don't use ACF Columns pro myself and the filter has been added by a contributor. Can you take a look and submit a PR?

**Comment by dbrabyn** [comment]
This is above my skill level I'm afraid. But their support say they are happy (support@admincolumns.com).

In the meanwhile, rolling back to v2.1.0 removes the conflict.

**Comment by orangecactus** [comment]
Just picking this up. The issues are in the file "acf-coutry.php".

1. First issue is the filter on line 36 is calling a protected method "admin_column" on line 170. This just need to be changed to a public method.

2.  The second issue is the method currently used on line 174 ... "$column->get_acf_field_option()" is now deprecated and needs to be replaced with "$column->get_field()->get_settings()['type']"

Implemented both these minor fixes locally and the issue has now been resolved. Can these fixed please be added into the main repo?

**Comment by nlemoine** [comment]
Thanks @orangecactus, can you submit a PR for this?

**Comment by orangecactus** [comment]
@nlemoine I believe this is done with this PR #65 ; they were only very minor changes.

**Comment by nlemoine** [comment]
This is now fixed in 3.0.1

https://github.com/nlemoine/acf-country/releases/tag/v3.0.1

Thanks to @orangecactus!
