### ISSUE TITLE
Multi select not working correctly

### ISSUE THREAD

**Issue by erralb** [nlemoine/acf-country#69]
Details
-------

 - WordPress version: 6.5.4
 - ACF version: 6.3.1.2. (Pro)
 - For UX/UI issues: MacOS, Chrome 125
 - Allow null: ?
 - Multiple values: true
 - Stylised UI: false
 - Condtional logic: false

The multiple selection javascript does not seem to work.

<img width="1465" alt="Screenshot 2024-06-24 at 14 44 58" src="https://github.com/nlemoine/acf-country/assets/790992/56edc7fa-ef7d-45c3-958c-f8eb6b0b3962">

No errors in the console.

Installed via composer, using Roots Sage 10 theme.

Any idea what's wrong ? Cheers

**Comment by nlemoine** [comment]
Looks like the native browser multiselect field? What if you command + click on multiple items?

**Comment by erralb** [comment]
Yes if I command + click on the field I can select multiple values.

But why don't I have the regular plugin display ?

![5bf05402-1631-11e7-8d7e-74d425a3eae4](https://github.com/nlemoine/acf-country/assets/790992/2381419a-f3a7-4157-aa52-71f9575ed131)

**Comment by nlemoine** [comment]
Because you disabled the "enhanced" UI:

```
Stylised UI: false
```

**Comment by erralb** [comment]
Damn sorry about that, I missed it with the new tabbed ACF field edition...

**Comment by nlemoine** [comment]
Ça arrive, aucun problème :)
