### ISSUE TITLE
Should not default to local country

### ISSUE THREAD

**Issue by robertandrews** [nlemoine/acf-country#7]
If a null value is allowed, why does the add-on default to pre-filling the local country?

I think you're assuming all use cases are for users to fill in a form to indicate their own country, but I imagine other use cases.

I think defaulting to a country should be an option, or not used.

Thanks.

**Comment by dotancohen** [comment]
You can set a different locale as the default:
    'type' => 'county',
    'default_value' => 'IL',

Setting the default locale as an empty string will instruct the plugin to mark the first country (Afganistan in English) as the default. Have no county selected does not seem to be supported, which effectively makes the country field a required field. That in itself is a bug.

**Comment by dotancohen** [comment]
The above issue is filed as Issue #8.

**Comment by dotancohen** [comment]
The above issue is filed as Issue #8.

**Comment by nlemoine** [comment]
Should be fixed now.
